### ISSUE TITLE
Implement details

### ISSUE THREAD

**Issue by zhengwsh** [roomylee/rcnn-text-classification#4]
Thanks for sharing code. It seems that your implement of context representation vectors (via Bi-RNN) differ from the original paper's (Equation 1&2). Have you compare the performance between them and what's your intuition? :)

**Comment by roomylee** [comment]
@zhengwsh 
If you use vanilla rnn cell, i think the implemented context vectors and the equation of original paper is the same. It could be used LSTM and GRU, then the model looks a bit better performance.

**Comment by sxlprince** [comment]
> @zhengwsh
> If you use vanilla rnn cell, i think the implemented context vectors and the equation of original paper is the same. It could be used LSTM and GRU, then the model looks a bit better performance.

Thanks for your code. But I have a problem. In the raw paper, theta represent all paramaters ,including "E; b(2); b(4); cl(w1); cr(wn); W (2);W (4); W (l); W (r); W (sl); W (sr)", these are all trained while training. But in your code, there are no "W (l); W (r); W (sl); W (sr)" and "cl(w1)" always setted to be zero vector because of the use of biRNN, is that a problem?Thanks!

**Comment by hbdongfeng** [comment]
i think it's different between them too。the paper's Equation 1 is W(l)cl(wi−1) + W(sl)e(wi−1)，but your code is W(l)cl(wi−1) + W(sl)e(wi)，can you understand what i mean ?
